# Generated by Django 3.2.9 on 2021-11-10 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=50, verbose_name='title')),
                ('duration', models.CharField(max_length=50, verbose_name='duration')),
                ('level', models.CharField(choices=[('1', 'beginner'), ('2', 'intermediate'), ('3', 'advanced')], max_length=1, verbose_name='level')),
                ('fee', models.IntegerField(default=None, verbose_name='fee')),
                ('description', models.TextField(default=None, verbose_name='description')),
                ('prerequisites', models.TextField(default=None, verbose_name='Prerequisites')),
                ('video_thumbnail', models.FileField(default=None, upload_to='courses/thumbnail/', verbose_name='video')),
                ('thumbnail', models.ImageField(default=None, upload_to='course/thumbnail/', verbose_name='thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='CourseLectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(default=None, max_length=50, verbose_name='title')),
                ('video', models.FileField(default=None, upload_to='course/videos', verbose_name='video')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='academy_app.courses', verbose_name='course_name')),
            ],
        ),
    ]
