# Generated by Django 3.2.9 on 2021-11-12 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='courses',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, upload_to='course/thumbnail/', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='video_thumbnail',
            field=models.FileField(blank=True, default=None, upload_to='course/thumbnail/', verbose_name='video thumbnail'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.BooleanField(verbose_name='payment status')),
                ('total_amount', models.IntegerField(verbose_name='amount')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='academy_app.courses', verbose_name='course_name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='academy_app.courses', verbose_name='course_name')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy_app.payment', verbose_name='payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
        ),
    ]
