# Generated by Django 3.2.9 on 2021-11-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0002_auto_20211112_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='address',
            field=models.TextField(default=None, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='first_name',
            field=models.CharField(default=None, max_length=50, verbose_name='first'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='last_name',
            field=models.CharField(default=None, max_length=50, verbose_name='last'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='phone',
            field=models.CharField(default=None, max_length=50, verbose_name='phone'),
        ),
    ]
