# Generated by Django 3.2.9 on 2021-11-13 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0004_auto_20211113_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='course_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academy_app.courses', verbose_name='course'),
        ),
    ]
