# Generated by Django 3.2.9 on 2021-11-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0005_auto_20211113_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=50, verbose_name='Bank')),
                ('card_number', models.CharField(max_length=50, verbose_name='ATM no.')),
                ('expiry', models.DateField(verbose_name='Expiry')),
                ('holder_name', models.CharField(max_length=50, verbose_name='Holder Name')),
            ],
        ),
    ]
