# Generated by Django 3.2.9 on 2021-11-13 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0006_paymentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academy_app.paymentdetail', verbose_name='payment detail'),
        ),
    ]
