# Generated by Django 3.2.9 on 2021-11-19 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0007_payment_payment_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='academy_app.courses', verbose_name='course_name')),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy_app.paymentdetail', verbose_name='payment detail'),
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy_app.curriculum')),
            ],
        ),
    ]
