# Generated by Django 3.2.9 on 2021-11-19 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0008_auto_20211119_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='academy_app.courses'),
        ),
    ]
