# Generated by Django 3.2.9 on 2021-11-19 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0012_alter_curriculum_subtopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='academy_app.courses', verbose_name='course_name')),
            ],
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='course',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='subtopic',
        ),
        migrations.DeleteModel(
            name='SubTopic',
        ),
        migrations.AddField(
            model_name='curriculumtopic',
            name='urriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy_app.curriculum'),
        ),
    ]
