# Generated by Django 3.2.9 on 2021-11-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0013_auto_20211119_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurriculumTopic',
            new_name='CurriculumSubTopic',
        ),
    ]
