# Generated by Django 3.2.9 on 2021-11-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_app', '0018_auto_20211119_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='description',
            field=models.CharField(default=None, max_length=50, verbose_name='Description'),
        ),
        migrations.DeleteModel(
            name='CurriculumSubTopic',
        ),
    ]
